import Head from 'next/head'
import classes from '../styles/globalStyle.module.scss'
import Carousel from '../components/carousel/carousel';
import PersonaCard from '../components/personas/personaCard';
import Communities from '../components/communities/communities';
import Events from '../components/events/events';
import Announcement from '../components/announcement/announcementCards';
import CTA from '../components/cta/cta';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Getting Started</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className={classes.section}>
          <Carousel />
        </section>
        <PersonaCard />
        <Events />
        <Communities />
        <Announcement />
        <CTA />
        {/* <Footer /> */}
        {/* <NavbarHover /> */}
      </main>
    </div>
  )
}
