import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar/Navbar';
import Carousel from '../components/Carousel/Carousel';
import PersonaCard from '../components/PersonaCard/index';
import Communities from '../components/Communities/index';
import Events from '../components/Events/index';
import Announcement from '../components/AnnouncementCards/index';

import "@fontsource/poppins"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Getting Started</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Carousel />
        <PersonaCard />
        <Events />
        <Communities />
        <Announcement />
      </main>
    </div>
  )
}
